*******************************************************************;
**  C:\COUNTS\programs\build2.pgm                                  ;
**  Proc Means from SAS File for each county                       ;
**  Year 2012                                                      ;
**  -- Dec23, 2012 --                                              ;
*******************************************************************;
OPTIONS NODATE;
OPTIONS number;
OPTIONS PAGESIZE=52;
* LIBNAME tcount 'c:\counts\tcount.sas';  
*******************************************************************;
** Note: Change SET COUNT.COUNT92 to; 
**              SET COUNT.COUNT93 for 1993 data Analysis;
*******************************************************************;
DATA tcount.OUT1IN; SET tcount.count15;
*******************************************************************;
 IF END7AM=0 THEN END7AM=.;
 IF END8AM=0 THEN END8AM=.;
 IF END9AM=0 THEN END9AM=.;
 IF END4PM=0 THEN END4PM=.;
 IF END5PM=0 THEN END5PM=.;
 IF END6PM=0 THEN END6PM=.;
 IF TOTAL24=0 THEN TOTAL24=.;
IF LEG='A' OR LEG='B' OR LEG='O' OR LEG='X' THEN DO;
  IF TOTAL24C='A' THEN DO;
     IF WEEKDAY='TUE' OR WEEKDAY='WED' OR WEEKDAY='THU' 
     THEN DO; OUTPUT tcount.OUT1IN; END;
  END;
END;
********* San Francisco County  **********;
DATA TEMP1; SET tcount.OUT1IN;
 IF COUNTY='SF' THEN OUTPUT TEMP1;
 PROC SORT DATA=temp1; BY route pm dir leg descrip;
 PROC MEANS maxdec=0;
 BY route pm dir leg descrip;
 VAR END7AM END8AM END9AM END4PM END5PM END6PM TOTAL24;
 TITLE1 'Statistical Summary';
 TITLE2 '2015 Observed Traffic Counts-State Highways-San Francisco County';
 TITLE3 'Count Days: Tuesdays, Wednesdays and Thursdays';
RUN;
********* San Mateo County  **********;
DATA TEMP1; SET tcount.OUT1IN;
 IF COUNTY='SM' THEN OUTPUT TEMP1;
 PROC SORT DATA=temp1; BY route pm dir leg descrip;
 PROC MEANS maxdec=0;
 BY route pm dir leg descrip;
 VAR END7AM END8AM END9AM END4PM END5PM END6PM TOTAL24;
 TITLE1 'Statistical Summary';
 TITLE2 '2015 Observed Traffic Counts-State Highways-San Mateo County';
 TITLE3 'Count Days: Tuesdays, Wednesdays and Thursdays';
RUN;
********* Santa Clara County  **********;
DATA TEMP1; SET tcount.OUT1IN;
 IF COUNTY='SCL' THEN OUTPUT TEMP1;
 PROC SORT DATA=temp1; BY route pm dir leg descrip;
 PROC MEANS maxdec=0;
 BY route pm dir leg descrip;
 VAR END7AM END8AM END9AM END4PM END5PM END6PM TOTAL24;
 TITLE1 'Statistical Summary';
 TITLE2 '2015 Observed Traffic Counts-State Highways-Santa Clara County';
 TITLE3 'Count Days: Tuesdays, Wednesdays and Thursdays';
RUN;
********** Alameda County ***************;
DATA TEMP1; SET tcount.OUT1IN;
 IF COUNTY='ALA' THEN OUTPUT TEMP1;
 PROC SORT DATA=temp1; BY route pm dir leg descrip;
 PROC MEANS maxdec=0;
** PROC UNIVARIATE;
 BY route pm dir leg descrip;
 VAR END7AM END8AM END9AM END4PM END5PM END6PM TOTAL24;
 TITLE1 'Statistical Summary';
 TITLE2 '2015 Observed Traffic Counts-State Highways-Alameda County';
 TITLE3 'Count Days: Tuesdays, Wednesdays and Thursdays';
**OUTPUT OUT=NEW MODE=end7am end8am end9am;
RUN;
********* Contra Costa County  **********;
DATA TEMP1; SET tcount.OUT1IN;
 IF COUNTY='CC' THEN OUTPUT TEMP1;
 PROC SORT DATA=temp1; BY route pm dir leg descrip;
 PROC MEANS maxdec=0;
 BY route pm dir leg descrip;
 VAR END7AM END8AM END9AM END4PM END5PM END6PM TOTAL24;
 TITLE1 'Statistical Summary';
 TITLE2 '2015 Observed Traffic Counts-State Highways-Contra Costa County';
 TITLE3 'Count Days: Tuesdays, Wednesdays and Thursdays';
RUN;
********* Solano County  **********;
DATA TEMP1; SET tcount.OUT1IN;
 IF COUNTY='SOL' THEN OUTPUT TEMP1;
 PROC SORT DATA=temp1; BY route pm dir leg descrip;
 PROC MEANS maxdec=0;
 BY route pm dir leg descrip;
 VAR END7AM END8AM END9AM END4PM END5PM END6PM TOTAL24;
 TITLE1 'Statistical Summary';
 TITLE2 '2015 Observed Traffic Counts-State Highways-Solano County';
 TITLE3 'Count Days: Tuesdays, Wednesdays and Thursdays';
RUN;
********* Napa County  **********;
DATA TEMP1; SET tcount.OUT1IN;
 IF COUNTY='NAP' THEN OUTPUT TEMP1;
 PROC SORT DATA=temp1; BY route pm dir leg descrip;
 PROC MEANS maxdec=0;
 BY route pm dir leg descrip;
 VAR END7AM END8AM END9AM END4PM END5PM END6PM TOTAL24;
 TITLE1 'Statistical Summary';
 TITLE2 '2015 Observed Traffic Counts-State Highways-Napa County';
 TITLE3 'Count Days: Tuesdays, Wednesdays and Thursdays';
RUN;
********* Sonoma County  **********;
DATA TEMP1; SET tcount.OUT1IN;
 IF COUNTY='SON' THEN OUTPUT TEMP1;
 PROC SORT DATA=temp1; BY route pm dir leg descrip;
 PROC MEANS maxdec=0;
 BY route pm dir leg descrip;
 VAR END7AM END8AM END9AM END4PM END5PM END6PM TOTAL24;
 TITLE1 'Statistical Summary';
 TITLE2 '2015 Observed Traffic Counts-State Highways-Sonoma County';
 TITLE3 'Count Days: Tuesdays, Wednesdays and Thursdays';
RUN;
********* Marin County  **********;
DATA TEMP1; SET tcount.OUT1IN;
 IF COUNTY='MRN' THEN OUTPUT TEMP1;
 PROC SORT DATA=temp1; BY route pm dir leg descrip;
 PROC MEANS maxdec=0;
 BY route pm dir leg descrip;
 VAR END7AM END8AM END9AM END4PM END5PM END6PM TOTAL24;
 TITLE1 'Statistical Summary';
 TITLE2 '2015 Observed Traffic Counts-State Highways-Marin County';
 TITLE3 'Count Days: Tuesdays, Wednesdays and Thursdays';
RUN;
********* San Joaquin County  **********;
DATA TEMP1; SET tcount.OUT1IN;
 IF COUNTY='SJ' THEN OUTPUT TEMP1;
 PROC SORT DATA=temp1; BY route pm dir leg descrip;
 PROC MEANS maxdec=0;
 BY route pm dir leg descrip;
 VAR END7AM END8AM END9AM END4PM END5PM END6PM TOTAL24;
 TITLE1 'Statistical Summary';
 TITLE2 '2015 Observed Traffic Counts-State Highways-San Joaquin County';
 TITLE3 'Count Days: Tuesdays, Wednesdays and Thursdays';
RUN;
********* Santa Cruz County  **********;
DATA TEMP1; SET tcount.OUT1IN;
 IF COUNTY='SCR' THEN OUTPUT TEMP1;
 PROC SORT DATA=temp1; BY route pm dir leg descrip;
 PROC MEANS maxdec=0;
 BY route pm dir leg descrip;
 VAR END7AM END8AM END9AM END4PM END5PM END6PM TOTAL24;
 TITLE1 'Statistical Summary';
 TITLE2 '2015 Observed Traffic Counts-State Highways-Santa Cruz County';
 TITLE3 'Count Days: Tuesdays, Wednesdays and Thursdays';
RUN;
********* Yolo County  **********;
DATA TEMP1; SET tcount.OUT1IN;
 IF COUNTY='YOL' THEN OUTPUT TEMP1;
 PROC SORT DATA=temp1; BY route pm dir leg descrip;
 PROC MEANS maxdec=0;
 BY route pm dir leg descrip;
 VAR END7AM END8AM END9AM END4PM END5PM END6PM TOTAL24;
 TITLE1 'Statistical Summary';
 TITLE2 '2015 Observed Traffic Counts-State Highways-Yolo County';
 TITLE3 'Count Days: Tuesdays, Wednesdays and Thursdays';
RUN;
*******************************************************************;
********* Lake County  **********;
DATA TEMP1; SET tcount.OUT1IN;
 IF COUNTY='LAK' THEN OUTPUT TEMP1;
 PROC SORT DATA=temp1; BY route pm dir leg descrip;
 PROC MEANS maxdec=0;
 BY route pm dir leg descrip;
 VAR END7AM END8AM END9AM END4PM END5PM END6PM TOTAL24;
 TITLE1 'Statistical Summary';
 TITLE2 '2015 Observed Traffic Counts-State Highways-Lake County';
 TITLE3 'Count Days: Tuesdays, Wednesdays and Thursdays';
RUN;
*******************************************************************;
********* San Benito County  **********;
DATA TEMP1; SET tcount.OUT1IN;
 IF COUNTY='SBT' THEN OUTPUT TEMP1;
 PROC SORT DATA=temp1; BY route pm dir leg descrip;
 PROC MEANS maxdec=0;
 BY route pm dir leg descrip;
 VAR END7AM END8AM END9AM END4PM END5PM END6PM TOTAL24;
 TITLE1 'Statistical Summary';
 TITLE2 '2015 Observed Traffic Counts-State Highways-San Benito County';
 TITLE3 'Count Days: Tuesdays, Wednesdays and Thursdays';
RUN;
*******************************************************************;

