*******************************************************************;
**  C:\COUNTS\PROGRAMS\build3AM.pgm                                ;
**  PROC PRINT from SAS File For AM Peak Period For Each County    ;
**  Year 2015                                                      ;
**  -- Dec. 23, 2015 --                                            ;
*******************************************************************;
**OPTIONS OBS=200;
OPTIONS NODATE;
OPTIONS number;
OPTIONS PAGESIZE=52;
LIBNAME tcount 'c:\counts\tcount.sas';  
*******************************************************************;
** Change COUNT90 to COUNT93 for 1993 Analysis;
*******************************************************************;
DATA tcount.OUT2IN; SET tcount.count15;
*******************************************************************;
 IF END7AM=0 THEN END7AM=.;
 IF END8AM=0 THEN END8AM=.;
 IF END9AM=0 THEN END9AM=.;
 IF TOTAL24=0 THEN TOTAL24=.;
IF LEG='A' OR LEG='B' OR LEG='O' OR LEG='X' THEN DO;
  IF TOTAL24C='A' THEN DO;
     IF WEEKDAY='TUE' OR WEEKDAY='WED' OR WEEKDAY='THU' 
     THEN DO; OUTPUT tcount.OUT2IN; END;
  END;
END;
********* San Francisco County **********;
DATA TEMP2; SET tcount.OUT2IN;
 IF COUNTY='SF' THEN OUTPUT TEMP2;
 PROC SORT DATA=temp2; BY route pm dir leg descrip;
 TITLE1 'Detailed 2015 Observed Traffic Counts-State Highways-San Francisco County';
 TITLE2 'Count Days: Tuesdays, Wednesdays and Thursdays';
 TITLE3 'A.M. Peak Period';
proc print;
ID route;
VAR pm dir leg date descrip end7am end8am end9am total24;
RUN;
********* San Mateo County **********;
DATA TEMP2; SET tcount.OUT2IN;
 IF COUNTY='SM' THEN OUTPUT TEMP2;
 PROC SORT DATA=temp2; BY route pm dir leg descrip;
 TITLE1 'Detailed 2015 Observed Traffic Counts-State Highways-San Mateo County';
 TITLE2 'Count Days: Tuesdays, Wednesdays and Thursdays';
 TITLE3 'A.M. Peak Period';
proc print;
ID route;
VAR pm dir leg date descrip end7am end8am end9am total24;
RUN;
********* Santa Clara County **********;
DATA TEMP2; SET tcount.OUT2IN;
 IF COUNTY='SCL' THEN OUTPUT TEMP2;
 PROC SORT DATA=temp2; BY route pm dir leg descrip;
 TITLE1 'Detailed 2015 Observed Traffic Counts-State Highways-Santa Clara County';
 TITLE2 'Count Days: Tuesdays, Wednesdays and Thursdays';
 TITLE3 'A.M. Peak Period';
proc print;
ID route;
VAR pm dir leg date descrip end7am end8am end9am total24;
RUN;
********** Alameda County ***************;
DATA TEMP2; SET tcount.OUT2IN;
 IF COUNTY='ALA' THEN OUTPUT TEMP2;
 PROC SORT DATA=temp2; BY route pm dir leg descrip;
 TITLE1 'Detailed 2015 Observed Traffic Counts-State Highways-Alameda County';
 TITLE2 'Count Days: Tuesdays, Wednesdays and Thursdays';
 TITLE3 'A.M. Peak Period';
proc print;
ID route;
VAR pm dir leg date descrip end7am end8am end9am total24;
RUN;
********* Contra Costa County **********;
DATA TEMP2; SET tcount.OUT2IN;
 IF COUNTY='CC' THEN OUTPUT TEMP2;
 PROC SORT DATA=temp2; BY route pm dir leg descrip;
 TITLE1 'Detailed 2015 Observed Traffic Counts-State Highways-Contra Costa County';
 TITLE2 'Count Days: Tuesdays, Wednesdays and Thursdays';
 TITLE3 'A.M. Peak Period';
proc print;
ID route;
VAR pm dir leg date descrip end7am end8am end9am total24;
RUN;
********* Solano County **********;
DATA TEMP2; SET tcount.OUT2IN;
 IF COUNTY='SOL' THEN OUTPUT TEMP2;
 PROC SORT DATA=temp2; BY route pm dir leg descrip;
 TITLE1 'Detailed 2015 Observed Traffic Counts-State Highways-Solano County';
 TITLE2 'Count Days: Tuesdays, Wednesdays and Thursdays';
 TITLE3 'A.M. Peak Period';
proc print;
ID route;
VAR pm dir leg date descrip end7am end8am end9am total24;
RUN;
********* Napa County **********;
DATA TEMP2; SET tcount.OUT2IN;
 IF COUNTY='NAP' THEN OUTPUT TEMP2;
 PROC SORT DATA=temp2; BY route pm dir leg descrip;
 TITLE1 'Detailed 2015 Observed Traffic Counts-State Highways-Napa County';
 TITLE2 'Count Days: Tuesdays, Wednesdays and Thursdays';
 TITLE3 'A.M. Peak Period';
proc print;
ID route;
VAR pm dir leg date descrip end7am end8am end9am total24;
RUN;
********* Sonoma County **********;
DATA TEMP2; SET tcount.OUT2IN;
 IF COUNTY='SON' THEN OUTPUT TEMP2;
 PROC SORT DATA=temp2; BY route pm dir leg descrip;
 TITLE1 'Detailed 2015 Observed Traffic Counts-State Highways-Sonoma County';
 TITLE2 'Count Days: Tuesdays, Wednesdays and Thursdays';
 TITLE3 'A.M. Peak Period';
proc print;
ID route;
VAR pm dir leg date descrip end7am end8am end9am total24;
RUN;
********* Marin County **********;
DATA TEMP2; SET tcount.OUT2IN;
 IF COUNTY='MRN' THEN OUTPUT TEMP2;
 PROC SORT DATA=temp2; BY route pm dir leg descrip;
 TITLE1 'Detailed 2015 Observed Traffic Counts-State Highways-Marin County';
 TITLE2 'Count Days: Tuesdays, Wednesdays and Thursdays';
 TITLE3 'A.M. Peak Period';
proc print;
ID route;
VAR pm dir leg date descrip end7am end8am end9am total24;
RUN;
********* San Joaquin County **********;
DATA TEMP2; SET tcount.OUT2IN;
 IF COUNTY='SJ' THEN OUTPUT TEMP2;
 PROC SORT DATA=temp2; BY route pm dir leg descrip;
 TITLE1 'Detailed 2015 Observed Traffic Counts-State Highways-San Joaquin County';
 TITLE2 'Count Days: Tuesdays, Wednesdays and Thursdays';
 TITLE3 'A.M. Peak Period';
proc print;
ID route;
VAR pm dir leg date descrip end7am end8am end9am total24;
RUN;
********* Santa Cruz County **********;
DATA TEMP2; SET tcount.OUT2IN;
 IF COUNTY='SCR' THEN OUTPUT TEMP2;
 PROC SORT DATA=temp2; BY route pm dir leg descrip;
 TITLE1 'Detailed 2015 Observed Traffic Counts-State Highways-Santa Cruz County';
 TITLE2 'Count Days: Tuesdays, Wednesdays and Thursdays';
 TITLE3 'A.M. Peak Period';
proc print;
ID route;
VAR pm dir leg date descrip end7am end8am end9am total24;
RUN;
********* Yolo County  **********;
DATA TEMP2; SET tcount.OUT2IN;
 IF COUNTY='YOL' THEN OUTPUT TEMP2;
 PROC SORT DATA=temp2; BY route pm dir leg descrip;
 TITLE1 'Detailed 2015 Observed Traffic Counts-State Highways-Yolo County';
 TITLE2 'Count Days: Tuesdays, Wednesdays and Thursdays';
 TITLE3 'A.M. Peak Period';
proc print;
ID route;
VAR pm dir leg date descrip end7am end8am end9am total24;
RUN;
*******************************************************************;
********* Lake County  **********;
DATA TEMP2; SET tcount.OUT2IN;
 IF COUNTY='LAK' THEN OUTPUT TEMP2;
 PROC SORT DATA=temp2; BY route pm dir leg descrip;
 TITLE1 'Detailed 2015 Observed Traffic Counts-State Highways-Lake County';
 TITLE2 'Count Days: Tuesdays, Wednesdays and Thursdays';
 TITLE3 'A.M. Peak Period';
proc print;
ID route;
VAR pm dir leg date descrip end7am end8am end9am total24;
RUN;
*******************************************************************;
********* San Benito County  **********;
DATA TEMP2; SET tcount.OUT2IN;
 IF COUNTY='SBT' THEN OUTPUT TEMP2;
 PROC SORT DATA=temp2; BY route pm dir leg descrip;
 TITLE1 'Detailed 2015 Observed Traffic Counts-State Highways-San Benito County';
 TITLE2 'Count Days: Tuesdays, Wednesdays and Thursdays';
 TITLE3 'A.M. Peak Period';
proc print;
ID route;
VAR pm dir leg date descrip end7am end8am end9am total24;
RUN;
*******************************************************************;
